- hosts: ans-nginx
  tasks:
    - name: Install nginx with dependencies
      apt:
        name: ['nginx=1.14.0-0ubuntu1.9']
        state: present
        update_cache: yes
#      with_items:
#        - nginx=1.14.0-0ubuntu1.9
      become: yes
      
    - name: copy the nginx config file
      copy:
        src: nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
    - name: copy the nginx config file
      copy:
        src: nginx/fwd.conf
        dest: /etc/nginx/conf.d
      become: yes
    - name: Create a directory if it does not exist
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
      become: yes
      #    - name: create directory for html
#      command:  mkdir -p /var/www/html
#      become: yes
    - name: copy the index.html
      copy:
        src: ./index.html
        dest: /var/www/html
      become: yes
      
    - name: Check NGINX configs
      shell: "/usr/sbin/nginx -t"
      register: nginx_config_status
    - name: NGINX test status
      debug:
        msg: "{{ nginx_config_status }}"
    - name: NGINX test status
      debug:
        msg: "{{ nginx_config_status.rc }}"
    - name: Service NGINX restart and enable on boot
      systemd:
        name: nginx
        state: restarted
        enabled: yes
        daemon_reload: yes
      when: nginx_config_status.rc == 0  
#    - name: restart nginx
#      service:
#        name: nginx
#        state: restarted
#      become: yes

