- hosts: ans-nginx
  tasks:
#    - name: ensure nginx is at the latest version
#      yum: name=nginx state=latest
#      become: yes
#    - name: ensure nginx is at the latest version
    - name: Install nginx with dependencies
      apt:
        name: ['nginx=1.14.0-0ubuntu1.9']
        state: present
        update_cache: yes
#      with_items:
#        - nginx=1.14.0-0ubuntu1.9
      become: yes
#    - name: install nginx if not installed
#      become: yes
#
#      apt:
#         name: nginx
#         state: 1.14.0
#         update_cache: yes
#    - name: install nginx if not installed
#      command:  amazon-linux-extras enable nginx1
#      become: yes
#    - name: start nginx
#      service:
#          name: nginx
#          state: started
#      become: yes
    - name: copy the nginx config file
      copy:
        src: ./nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
    - name: copy the nginx config file
      copy:
        src: ./upstr.conf
        dest: /etc/nginx/conf.d
      become: yes
    - name: Create a directory if it does not exist
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
      become: yes
      #    - name: create directory for html
#      command:  mkdir -p /var/www/html
#      become: yes
    - name: copy the index.html
      copy:
        src: ./index.html
        dest: /var/www/html
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

