- hosts: ans-app
  tasks:
    - name: Install nodejs
      apt:
        name: ['npm=3.5.2-0ubuntu4']
        state: present
        update_cache: yes
      become: yes
#    - name: Create a directory for web app
#      file:
#        path: "{{DATA}}"
#        state: directory
#        mode: '0755'
#      become: yes
    - name: create user node-red
      become: yes
      user:
        name: node-red
        shell: /bin/bash
        home: "{{DATA}}"
    - name: Install pm2
      become: yes
      npm: name=pm2 global=yes production=yes
    - name: Install node-red
      npm: name=node-red global=yes production=yes
      become: yes
    - name: Install node-red-contrib-re-postgres
      npm: name=node-red-contrib-re-postgres global=yes production=yes
      become: yes
    - name: copy the web app config file
      copy:
        src: ./flows.json
        dest: {{DATA}}/flows.json
      become: yes
      become_user: node-red
    - name: copy the web app config file
      copy:
        src: ./flows_cred.json
        dest: {{DATA}}/flows_cred.json
      become: yes
      become_user: node-red
    - name: copy the web app config file
      copy:
        src: ./settings.js
        dest: {{DATA}}/settings.js
      become: yes
      become_user: node-red
    - name: set postgresql ip
      replace:
        path: {{DATA}}/flows.json
        regexp: '^(\s*"hostname":\s+")pg_host(",\s*)$'
        replace: '\1{{pg_host}}\2'
    - name: run web application
      shell: "pm2 restart node-red -- --userDir /data --port 8080"
      become: yes
      become_user: node-red
