- hosts: ans-app
  tasks:
    - name: Install nodejs
      apt:
        name: ['npm=3.5.2-0ubuntu4']
        state: present
        update_cache: yes
      become: yes
    - name: Create a directory for web app
      file:
        path: "{{DATA}}"
        state: directory
        mode: '0755'
      become: yes
    - name: create user node-red
      become: yes
      user:
        name: node-red
        shell: /bin/bash
        home: "{{DATA}}"
    - name: Install pm2
      npm: name=pm2 global=yes production=yes
    - name: Install node-red
      npm: name=node-red global=yes production=yes
    - name: Install node-red-contrib-re-postgres
      npm: name=node-red-contrib-re-postgres global=yes production=yes
