- hosts: ans-app
  tasks:
    - name: Install nodejs
      apt:
        name: ['npm=3.5.2-0ubuntu4']
        state: present
        update_cache: yes
      become: yes
    - name: Create a directory for web app
      file:
        path: "{{DATA}}"
        state: directory
        mode: '0755'
      become: yes
    - name: create user node-red
      become: yes
      user:
        name: node-red
        shell: /bin/bash
        groups: node-red
        append: yes
        home: "{{DATA}}"
