- hosts: ans-app
  tasks:
    - name: Install nodejs
      apt:
        name: ['npm=3.5.2-0ubuntu4']
        state: present
        update_cache: yes
      become: yes
    - name: Create a directory for database
      file:
        path: "{{DATA}}"
        state: directory
        mode: '0755'
      become: yes 
