- hosts: web_app
  tasks:
    - name: Install nodejs
      apt:
        name: ['npm=3.5.2-0ubuntu4']
        state: present
        update_cache: yes
      become: yes
      
    - name: create user node-red
      become: yes
      user:
        name: node-red
        shell: /bin/bash
        home: "{{DATA}}"
        
    - name: Install pm2
      become: yes
      npm: name=pm2 global=yes production=yes
      
    - name: Install node-red
      npm: name=node-red global=yes production=yes
      become: yes
      
    - name: Install node-red-contrib-re-postgres
      npm: name=node-red-contrib-re-postgres global=yes production=yes
      become: yes
      
    - name: Check init run
      stat:
        path: "{{DATA}}/settings.js"
      register: not_init_run
      become: yes
      
#    - name: show answer 
#      debug:
#        msg: "{{ not_init_run.stat.exists }}"
      
    - name: copy the web app config file
      copy:
        src: ./flows.json
        dest: "{{DATA}}/flows.json"
      become: yes
      become_user: node-red
      
    - name: set postgresql ip
      replace:
        path: "{{DATA}}/flows.json"
        regexp: '^\s*"hostname":\s*"\d+\.\d+\.\d+\.\d+",\s*$'
        replace: '        "hostname": "{{hostvars.web_app.ansible_host}}",'
      become: yes
      become_user: node-red
      
    - name: copy the web app config file
      copy:
        src: ./flows_cred.json
        dest: "{{DATA}}/flows_cred.json"
      become: yes
      become_user: node-red
      
    - name: copy the web app config file
      copy:
        src: ./settings.js
        dest: "{{DATA}}/settings.js"
      become: yes
      become_user: node-red
      
    - name: load credential secret
      include_vars:
        file: encrypted_supersecretkey.yml
        
    - name: set credential secret
      replace:
        path: "{{DATA}}/settings.js"
        regexp: '^\s*credentialSecret:\s*".+",\s*$'
        replace: '    credentialSecret: "{{encrypted_supersecretkey}}",'
      become: yes
      become_user: node-red

    - name: init run
      shell: "pm2 start node-red -- --userDir {{DATA}} --port 8080"
      when: not not_init_run.stat.exists 
      become: yes
      become_user: node-red

    - name: run web application
      shell: "pm2 restart node-red -- --userDir {{DATA}} --port 8080"
      become: yes
      become_user: node-red
